# 系统信息
setting:
  title: 'Partake'
  description: '^_^ 发现您喜欢的开源项目！'
  api_vnd: 'partake.v0.1'
  secret: 'gwb2vp6tk1inpspztkexdj2egxmegu'
  static_url: ''

# 数据库配置
db:
  redis: 'redis://127.0.0.1'
  mongodb: 'mongodb://127.0.0.1/partake'

# 搜索引擎配置
elasticsearch:
  host: 'localhost'
  port: '9200'

# 又拍云
upyun:
  api: 'http://v0.api.upyun.com'
  buckets:
    - name: 'partake-images'
      secret: 'Zetk/7ysh3W2Js7yMybtmNEzOyU='
      url: 'http://partake-images.b0.upaiyun.com'

# 用户认证
auth:
  github:
    client_id: 'c6951da9e1ed5e3e22f9'
    client_secret: 'b6ae40111939ff3f3a456c9c35cf2a950767cdfb'
    callback_url: 'http://localhost:5000/auth/github/callback'


# 公共数据
data:
  # 授权协议
  agreements: [Apache Licence, BSD, GPL, LGPL, MIT, MPL, CDDL, EPL]
  # 开发语言
  languages: [Swift, Java, C/C++, Objective-C, PHP, Perl, Python, Ruby, C#,
              .NET, ASP, Google Go, D语言, Groovy, Scala, JavaScript, HTML/CSS,
              ActionScript, VBScript, Delphi/Pascal, Basic, ErLang, COBOL,
              Fortran, Lua, SHELL, Smalltalk, 汇编, Sliverlight, Lisp]
  # 操作系统
  systems: [跨平台, Windows, Linux, BSD, UNIX, OS X, Symbian, J2ME, 嵌入式, Android,
            iPhone/iPad/iPod, Windows Phone/Mobile, Meego, Moblin, Firefox OS]
  # 格言警句
  aphorisms:
    - 人们倾向于记住最先发生的事情和最后发生的事情
    - 报价之后，不再说话
    - 如果你问了别人一个问题，然后他们回答了一半，你等着，他们会说完的
    - 人们最终记住的不是你说过的话，而是你让他们产生的感觉
    - 当你学习新东西的时候，尝试着教给朋友们，或者让他们问你相关的问题
    - 装出牛逼的样子，直到你做到了；信心比知道更重要
    - 你假装成什么样子，你最终就会成为什么样子
    - 不要说“我觉得”、“我认为”，除非真的有必要
    - 第一次饭，第一支酒，你请
    - 如果你想和某人建立密切的关系，或者获得某人的信任，学习他的身体的姿势
    - 真正的输家是那些害怕失败，连尝试都不敢的人
    - 心之何如，有似万丈迷津，遥亘千里，其中并无舟子可以渡人，除了自渡，他人爱莫能助
    - 当你重获新生的时候，我愿你此生风霜不在
    - 凡是能重获新生的人都是有大能量的人

