# 数据库配置
db:
  redis: 'redis://127.0.0.1'
  mongodb: 'mongodb://127.0.0.1/partake'

#用户认证
auth:
  github:
    client_id: '0010da5d410780f81630'
    client_secret: '6d5d72cd04c40e45f3ecf4a264a5a4e2b9c087c7'
    callback_url: 'http://partake.top/auth/github/callback'
